name: kbuddy_flutter
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_regex: ^0.0.3
  flutter_riverpod: ^2.5.1
  flutter_secure_storage: ^9.2.2
  go_router: ^14.2.0
  intl: ^0.19.0
  json_annotation: ^4.9.0
  logger: ^2.3.0
  pretty_dio_logger: ^1.3.1
  retrofit: ^4.1.0
  riverpod_annotation: ^2.3.5
  checkbox_grouped: ^2.0.0

dev_dependencies:
  build_runner: ^2.4.11
  custom_lint: ^0.6.4
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  json_serializable: ^6.8.0
  retrofit_generator: ^8.1.0
  riverpod_generator: ^2.4.0
  riverpod_lint: ^2.3.10

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - asset/icons/
    - asset/alert/
    - asset/sns_logo/
    - asset/bottom_nav_bar/
    - asset/alert/alarm/
    # - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Montserrat
      fonts:
        - asset: asset/fonts/Montserrat/Montserrat-Light.ttf
          weight: 400
        - asset: asset/fonts/Montserrat/Montserrat-Bold.ttf
          weight: 800
    - family: Roboto
      fonts:
        - asset: asset/fonts/Roboto/Roboto-Light.ttf
          weight: 400
        - asset: asset/fonts/Roboto/Roboto-Medium.ttf
          weight: 500
        - asset: asset/fonts/Roboto/Roboto-Regular.ttf
          weight: 600
        - asset: asset/fonts/Roboto/Roboto-Bold.ttf
          weight: 700
    - family: RobotoLabel
      fonts:
        - asset: asset/fonts/Roboto/Roboto-Light.ttf
          weight: 500
        - asset: asset/fonts/Roboto/Roboto-Bold.ttf
          weight: 600

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
